### ISSUE TITLE
Keep OTBD and OTHH on the same display view.

### ISSUE THREAD

**Issue by SamHep0803** [Arabian-vACC/OTDF-Doha-FIR-Controller-Pack#1]
OTBD and OTHH both use the same ground layouts. It's confusing sometimes to switch between them accidentally be zoomed in on the wrong airport and not see any taxiways, stand labels etc.. Would it not make more sense for them to be combined into one display and just switch between them?

**Comment by DedpewlControl** [comment]
The way that it is set up is that there are two different ASR displays which are centered at OTHH and OTBD respectively. That is why it is set that way so when you do F1+2 it goes to HH and F1+3 is BD. You should be avoiding from scrolling to the other airport on the HH display for instance.

**Comment by SamHep0803** [comment]
Roger, sounds good.
